# Site settings
title: zhoujing的博客
header-img: img/home-bg.jpg
email: zhou---jing.hotmail.com
description: "无愧过往  无畏将来"
baseurl: ""
url: "https://zhou---jing.github.io"
github_username:  zhou---jing

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
